#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &
nm-applet &
cbattion &
redshift -l 5.42:-75.10 &
$HOME/.config/polybar/launch.sh
feh --bg-fill /usr/share/backgrounds/bspwm/99791.jpg

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d                       
bspc monitor HDMI-1 -d www dev term ref sys


bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          5
bspc config focused_border_color '#a151d3'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config external_rules_command ~/Android/emu.sh
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


